/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConversionsRouteImport } from './routes/_authenticated/conversions'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedSquadRouteImport } from './routes/_authenticated/squad'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedTrophiesRouteImport } from './routes/_authenticated/trophies'
import { Route as AuthenticatedWellbeingRouteImport } from './routes/_authenticated/wellbeing'
import { Route as JoinInviteCodeRouteImport } from './routes/join.$inviteCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConversionsRoute =
  AuthenticatedConversionsRouteImport.update({
    id: '/conversions',
    path: '/conversions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSquadRoute = AuthenticatedSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrophiesRoute = AuthenticatedTrophiesRouteImport.update({
  id: '/trophies',
  path: '/trophies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWellbeingRoute = AuthenticatedWellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JoinInviteCodeRoute = JoinInviteCodeRouteImport.update({
  id: '/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conversions': typeof AuthenticatedConversionsRoute
  '/me': typeof AuthenticatedMeRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/squad': typeof AuthenticatedSquadRoute
  '/today': typeof AuthenticatedTodayRoute
  '/trophies': typeof AuthenticatedTrophiesRoute
  '/wellbeing': typeof AuthenticatedWellbeingRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conversions': typeof AuthenticatedConversionsRoute
  '/me': typeof AuthenticatedMeRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/squad': typeof AuthenticatedSquadRoute
  '/today': typeof AuthenticatedTodayRoute
  '/trophies': typeof AuthenticatedTrophiesRoute
  '/wellbeing': typeof AuthenticatedWellbeingRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/conversions': typeof AuthenticatedConversionsRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/squad': typeof AuthenticatedSquadRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/trophies': typeof AuthenticatedTrophiesRoute
  '/_authenticated/wellbeing': typeof AuthenticatedWellbeingRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conversions'
    | '/me'
    | '/planner'
    | '/reminders'
    | '/squad'
    | '/today'
    | '/trophies'
    | '/wellbeing'
    | '/join/$inviteCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conversions'
    | '/me'
    | '/planner'
    | '/reminders'
    | '/squad'
    | '/today'
    | '/trophies'
    | '/wellbeing'
    | '/join/$inviteCode'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/conversions'
    | '/_authenticated/me'
    | '/_authenticated/planner'
    | '/_authenticated/reminders'
    | '/_authenticated/squad'
    | '/_authenticated/today'
    | '/_authenticated/trophies'
    | '/_authenticated/wellbeing'
    | '/join/$inviteCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinInviteCodeRoute: typeof JoinInviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conversions': {
      id: '/_authenticated/conversions'
      path: '/conversions'
      fullPath: '/conversions'
      preLoaderRoute: typeof AuthenticatedConversionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/squad': {
      id: '/_authenticated/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof AuthenticatedSquadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trophies': {
      id: '/_authenticated/trophies'
      path: '/trophies'
      fullPath: '/trophies'
      preLoaderRoute: typeof AuthenticatedTrophiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wellbeing': {
      id: '/_authenticated/wellbeing'
      path: '/wellbeing'
      fullPath: '/wellbeing'
      preLoaderRoute: typeof AuthenticatedWellbeingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join/$inviteCode': {
      id: '/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof JoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConversionsRoute: typeof AuthenticatedConversionsRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedSquadRoute: typeof AuthenticatedSquadRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedTrophiesRoute: typeof AuthenticatedTrophiesRoute
  AuthenticatedWellbeingRoute: typeof AuthenticatedWellbeingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConversionsRoute: AuthenticatedConversionsRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedSquadRoute: AuthenticatedSquadRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedTrophiesRoute: AuthenticatedTrophiesRoute,
  AuthenticatedWellbeingRoute: AuthenticatedWellbeingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinInviteCodeRoute: JoinInviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
